### ISSUE TITLE
Doesn't accept Numbers for list indices

### ISSUE THREAD

**Issue by moird** [jorisroovers/yamlpal#1]
yamlpal find -f examples/sample1.yml "product/0/"
Traceback (most recent call last):
  File "/Users/daniel/.virtualenvs/yamlpal/bin/yamlpal", line 9, in <module>
    load_entry_point('yamlpal==0.2.0.dev0', 'console_scripts', 'yamlpal')()
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/yamlpal/cli.py", line 101, in find
    found = find_in_file(needle, file, format)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/yamlpal/cli.py", line 114, in find_in_file
    element = find_element(data, needle)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/yamlpal/cli.py", line 205, in find_element
    node = node[key]
TypeError: list indices must be integers, not unicode

**Comment by jorisroovers** [comment]
We should do something about the error.

However, to access indices you should use ```product[0]```, similar to xpath. This does work:
```bash
$~/repos/yamlpal (master)$ yamlpal find -f examples/sample1.yml product[0]
0: {
    "sku": "BL394D",
    "price": "450.0",
    "description": "Basketball",
    "quantity": "4"
}
```
Note that json-based output is a known issue, see https://github.com/jorisroovers/yamlpal/blob/01a85c350adc063a5b291e72d63385aaf2e619ed/yamlpal/cli.py#L134

If you use ```product/0```, you're actually accessing the key called '0' under product, matching the ```0:foobar``` keypair from a yamlfile that looks like:
```yaml
product:
  0: foobar
  1: hurdur
```
Since the example file isn't structured like this, your query doesn't work :-)

I'll keep this around to do something about the error though
