### ISSUE TITLE
Return sub elements of a list.

### ISSUE THREAD

**Issue by moird** [jorisroovers/yamlpal#2]
When wanting to return all of a particular list, ie in the sample there is a list of products that all have the field sku, if I want to find all the skus I would expect to access it like: product/*/sku and get a list of all the skus returned.

yamlpal find -f examples/sample1.yml "product/*/sku"
Traceback (most recent call last):
  File "/Users/daniel/.virtualenvs/yamlpal/bin/yamlpal", line 9, in <module>
    load_entry_point('yamlpal==0.2.0.dev0', 'console_scripts', 'yamlpal')()
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/yamlpal/cli.py", line 101, in find
    found = find_in_file(needle, file, format)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/yamlpal/cli.py", line 114, in find_in_file
    element = find_element(data, needle)
  File "/Users/daniel/.virtualenvs/yamlpal/lib/python2.7/site-packages/yamlpal/cli.py", line 205, in find_element
    node = node[key]
TypeError: list indices must be integers, not unicode

**Comment by jorisroovers** [comment]
Wildcard search is unsupported. I can see this would be useful though. Marked  as enhancement.
